function output_txt = customdatatip(obj,event_obj, x_vals, y_vals, labels, exp_folder)
    pos = get(event_obj, 'Position');
    points = [x_vals'; y_vals'];
    point = [pos(1); pos(2)];
    indices = find(sum(points == point) == 2);
    label = num2str(labels(indices)');
    plotExperiment(labels(indices), exp_folder)
    output_txt = {...
    ['X: ', num2str(pos(1),4)]...
    ['Y: ', num2str(pos(2),4)] ...
    ['Experiment[s]: ', label]...
};